### ISSUE TITLE
Using Single Pallette Breaks The "Other" Category

### ISSUE THREAD

**Issue by joecooldoo** [WarpedWartWars/Text-Based_Snap#2]
I recommend setting the default for single pallette to false.

**Comment by joecooldoo** [comment]
I have removed the option to change it to the single palette, but I can't find out how to make Single Palette off by default.

**Comment by WarpedWartWars** [comment]
I want unified palette on by default, and easily chooseable.

As for the title, I'll just add blocks to the Other cat.

**Comment by WarpedWartWars** [comment]
I have made it not go to WARP, a ring, or SCRIPT VARIABLES, but unless you have a block (that isn't one of those) in it, it does nothing.

**Comment by WarpedWartWars** [comment]
Fixed!
